// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'dot': string;
  'green': string;
  'grey': string;
  'listing': string;
  'orange': string;
  'red': string;
  'row': string;
  'status': string;
}
export const cssExports: CssExports;
export default cssExports;
